[package]
name = "hello"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.5"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
