[package]
name = "hello-neon"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
hello = { path = "../../rust/hello" }
thiserror = "1.0"

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]
