# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/cpp/hello"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/nodejs/hello"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/python/hello"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/rust/hello"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/nodejs/hello"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/python/hello"
    schedule:
      interval: "daily"
