# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - directory: "/"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/cpp/hello"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/nodejs/hello"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/nodejs/hello"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/python/hello"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/python/hello"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"

  - directory: "/rust/hello"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/wasm/hello-emscripten/tests"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/wasm/hello-wasm-pack"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"

  - directory: "/wasm/hello-wasm-pack/tests"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
