[env]
PROJECT_NAME = "hello"
l = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "/", mapping = { "windows" = "\\" } }

[tasks.build]
clear = true
run_task = [{ name = ["pre-build", "main-build", "post-build"] }]

[tasks.pre-build]

[tasks.main-build]
script = "cargo build"

[tasks.post-build]

[tasks.test]
clear = true
script = "cargo test --lib -- --nocapture"

[tasks.watch]
extend = "test"
watch = true
