[package]
name = "hello-wasm-pack"
version.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
hello = { path = "../../rust/hello" }
js-sys = "0.3"
wasm-bindgen = "0.2"
