[package]
name = "hello-wasm-pack"
version = "0.1.0"
publish = false
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hello = { path = "../../rust/hello" }
js-sys = "0.3"
wasm-bindgen = "0.2"
