[package]
name = "hello-emscripten"
version.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
hello-cpp = { path = "../../cpp/hello" }

[build-dependencies]
cbindgen = "0.24"
