build:
    cmake \
        -S . \
        -B build \
        -D HELLO_INCLUDE_DIR="{{absolute_path("include")}}" \
        -D HELLO_LIB_DIR="{{absolute_path("lib")}}"

    rustup target add wasm32-unknown-emscripten
    cargo build
    mkdir -p lib
    cp ../../target/wasm32-unknown-emscripten/debug/libhello_emscripten.a lib/libhello_emscripten.a

    cmake --build build
    cmake --install build --prefix hello

test: build
    cd tests && \
    npm install && \
    npm test

test-quick:
    cd tests && \
    npm test
