build:
    cmake -S. -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=1
    cmake --build build
    cmake --install build --prefix hello

test: build
    #!/usr/bin/env bash
    cd tests
    npm install
    npm test
