[package]
name = "hello-cpp"
version = "0.1.0"
publish = false
edition = "2021"
rust-version = "1.64"

[dependencies]
thiserror = "1.0"
hello = { path = "../../rust/hello" }

[build-dependencies]
cbindgen = "0.24"
