[package]
name = "hello-cpp"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
libc = "0.2"
thiserror = "1.0"
hello = { path = "../../rust/hello" }

[build-dependencies]
cbindgen = "0.23"
