[package]
name = "hello-cpp"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
thiserror = "1.0"
hello = { path = "../../rust/hello" }

[build-dependencies]
cbindgen = "0.22"
