[package]
name = "hello_cpp"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "hello"
crate-type = ["cdylib"]

[dependencies]
error-chain = "0.12"
libc = "0.2"
hello = {path = "../../rust/hello"}

[build-dependencies]
cbindgen = "0.17"
