build-cdylib:
    just --justfile justfile-cdylib build

build-staticlib:
    just --justfile justfile-staticlib build

build: build-cdylib build-staticlib

test-cdylib:
    just --justfile justfile-cdylib test

test-staticlib:
    just --justfile justfile-staticlib test

test: test-cdylib test-staticlib
