extend = "../../Makefile.toml"

[tasks.pre-build]
script = '''
#!@shell
mkdir -p ${PROJECT_NAME}/lib || exit 0
'''

[tasks.post-build.windows]
script = '''
#!@shell
cp ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/debug/${CARGO_MAKE_CRATE_FS_NAME}.dll ${PROJECT_NAME}/lib/${CARGO_MAKE_CRATE_FS_NAME}.dll || exit $?
cp ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/debug/${CARGO_MAKE_CRATE_FS_NAME}.dll.lib ${PROJECT_NAME}/lib/${CARGO_MAKE_CRATE_FS_NAME}.lib || exit $?
'''

[tasks.post-build.mac]
script = "cp ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/debug/lib${CARGO_MAKE_CRATE_FS_NAME}.dylib ${PROJECT_NAME}/lib/lib${CARGO_MAKE_CRATE_FS_NAME}.dylib"

[tasks.post-build.linux]
script = "cp ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/debug/lib${CARGO_MAKE_CRATE_FS_NAME}.so ${PROJECT_NAME}/lib/lib${CARGO_MAKE_CRATE_FS_NAME}.so"

[tasks.test]
dependencies = ["build"]
script = '''
#!@shell
cmake -S . -B build || exit $?
cmake --build build --clean-first || exit $?
ctest --test-dir build -V || exit $?
'''
