extend = "../../Makefile.toml"

[env]
PATH = {source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "./bin:${PATH}", mapping = {"windows" = "./bin;${PATH}"}}
SOURCE_LIB_FILE_NAME = {source = "${CARGO_MAKE_RUST_TARGET_OS}", mapping = {"windows" = "${CARGO_MAKE_CRATE_NAME}.dll", "macos" = "lib${CARGO_MAKE_CRATE_NAME}.dylib", "linux" = "lib${CARGO_MAKE_CRATE_NAME}.so"}}
TARGET_LIB_FILE_NAME = {source = "${CARGO_MAKE_RUST_TARGET_OS}", mapping = {"windows" = "${PROJECT_NAME}.dll", "macos" = "lib${PROJECT_NAME}.dylib", "linux" = "lib${PROJECT_NAME}.so"}}

[tasks.cbindgen]
install_script = '''
#!@shell
cargo install cbindgen --root .
'''
script = '''
#!@shell
cbindgen --crate ${CARGO_MAKE_CRATE_NAME} --output ${PROJECT_NAME}/include/${PROJECT_NAME}.h
'''

[tasks.build]
clear = true
dependencies = ["cbindgen"]
script = '''
#!@shell
cargo build || exit $?
mkdir -p ${PROJECT_NAME}/lib
cp ../../target/debug/${SOURCE_LIB_FILE_NAME} ${PROJECT_NAME}/lib/${TARGET_LIB_FILE_NAME} || exit $?
'''

[tasks.test]
clear = true
dependencies = ["build"]
script = '''
#!@shell
cmake -S . -B build || exit $?
cmake --build build || exit $?
cd build && ctest -V || exit $?
'''
