[package]
name = "hello-nodejs"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "1"
napi-derive = "2"
hello = { path = "../../rust/hello" }
thiserror = "1.0"

[build-dependencies]
napi-build = "1"
