[package]
name = "hello-nodejs"
version = "0.1.0"
publish = false
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"
hello = { path = "../../rust/hello" }
thiserror = "1.0"

[build-dependencies]
napi-build = "2"
