extend = "../../Makefile.toml"

[tasks.pre-build]
script = "mkdir -p hello"

[tasks.main-build]
install_script = "npm install"
script = "npm run-script build"

[tasks.test]
dependencies = ["build"]
script = "npm test"
