extend = "../../Makefile.toml"

[tasks.pre-build]
script = '''
#!@shell
mkdir -p ${PROJECT_NAME} || exit 0
'''

[tasks.main-build]
install_script = "npm ci"
script = "npm run-script build"

[tasks.test]
dependencies = ["build"]
script = "npm test"
