[package]
name = "hello-python"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
thiserror = "1.0"
hello = { path = "../../rust/hello" }

[dependencies.pyo3]
version = "0.15"
features = ["extension-module"]
