[package]
name = "hello_python"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "hello"
crate-type = ["cdylib"]

[dependencies]
error-chain = "0.12.4"
hello = {path = "../../rust/hello"}

[dependencies.pyo3]
version = "0.13"
features = ["extension-module"]
