[package]
name = "hello-python"
version = "0.1.0"
publish = false
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
thiserror = "1.0"
hello = { path = "../../rust/hello" }

[dependencies.pyo3]
version = "0.17"
features = ["extension-module"]
