export PYO3_PYTHON := if os() == "windows" {
    absolute_path(".venv/Scripts/python.exe")
} else {
    absolute_path(".venv/bin/python")
}

build: && post-build
    poetry install
    cargo build

[linux]
post-build:
    cp \
        ../../target/debug/libhello_python.so \
        hello/hello.so

[macos]
post-build:
    cp \
        ../../target/debug/libhello_python.dylib \
        hello/hello.so

[windows]
post-build:
    cp \
        ../../target/debug/hello_python.dll \
        hello/hello.pyd

test: build
    poetry run pytest
