export PYO3_PYTHON := if os() == "windows" {
    justfile_directory() + "/.venv/Scripts/python.exe"
} else {
    justfile_directory() + "/.venv/bin/python"
}

SOURCE_LIB_FILE_NAME := if os() == "windows" {
    "hello_python.dll"
} else if os() == "macos" {
    "libhello_python.dylib"
} else {
    "libhello_python.so"
}

TARGET_LIB_FILE_NAME := if os() == "windows" {
    "hello.pyd"
} else {
    "hello.so"
}

build:
    poetry install
    cargo build
    cp ../../target/debug/{{SOURCE_LIB_FILE_NAME}} hello/{{TARGET_LIB_FILE_NAME}}

test: build
    poetry run pytest -s
