[env]
PYO3_PYTHON = {source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "${CARGO_MAKE_WORKING_DIRECTORY}/.venv/bin/python", mapping = {"windows" = "${CARGO_MAKE_WORKING_DIRECTORY}/.venv/Scripts/python.exe"}}
SOURCE_FILE_NAME = {source = "${CARGO_MAKE_RUST_TARGET_OS}", mapping = {"windows" = "hello_python.dll", "macos" = "libhello_python.dylib", "linux" = "libhello_python.so"}}
TARGET_FILE_NAME = {source = "${CARGO_MAKE_RUST_TARGET_OS}", mapping = {"windows" = "hello.pyd", "macos" = "hello.so", "linux" = "hello.so"}}

[tasks.build]
clear = true
install_script = "poetry install"
script = '''
#!@shell
cargo build || exit $?
cp ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/debug/${SOURCE_FILE_NAME} hello/${TARGET_FILE_NAME} || exit $?
'''

[tasks.test]
clear = true
dependencies = ["build"]
script = '''
#!@shell
cargo test || exit $?
poetry run pytest -s || exit $?
'''
