name: Test Linux AArch64

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          install: |
            apt-get update -y
            apt-get install -y curl

            # Rust
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y

            # just
            curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash

            # CMake
            apt-get install -y cmake

            # Node.js
            curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
            apt-get install -y nodejs

            # Python
            apt-get install -y python3.8 python3.8-distutils
            update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1

            # Poetry
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          run: |
            source $HOME/.cargo/env
            source $HOME/.poetry/env

            # Check versions
            cargo -V
            just -V
            cmake --version
            node -v
            python -V
            poetry -V
