name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        target:
          - cpp/hello
          - nodejs/hello-napi
          - nodejs/hello-neon
          - python/hello
          - rust/hello

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - if: ${{ startsWith(matrix.target, 'nodejs') }}
        name: Setup Node
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 14

      - if: ${{ startsWith(matrix.target, 'python') }}
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            **/target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - if: ${{ startsWith(matrix.target, 'python') }}
        name: Cache Poetry
        uses: actions/cache@v2
        with:
          path: "**/.venv"
          key: ${{ runner.os }}-${{ matrix.target }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.target }}-poetry-

      - if: ${{ startsWith(matrix.target, 'nodejs') }}
        name: Cache Node
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.target }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.target }}-node-

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1

      - if: ${{ startsWith(matrix.target, 'python') }}
        name: Install Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Test
        working-directory: ${{ matrix.target }}
        run: cargo make test
